# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: postgres_db
  port: 5432

mysql: &mysql
  adapter: mysql2
  encoding: utf8
  username: root
  password: root
  host: mysql_db
  port: 3306

development:
  primary:
    <<: <%= ENV['DB_MODE'] ? "*#{ENV['DB_MODE']}" : "*mysql" %>
    database: moviestore_development
  shard_one:
    <<: <%= ENV['DB_MODE'] ? "*#{ENV['DB_MODE']}" : "*mysql" %>
    database: moviestore_development_shard_one
    migration_paths: db/migrate_shards
  shard_two:
    <<: <%= ENV['DB_MODE'] ? "*#{ENV['DB_MODE']}" : "*mysql" %>
    database: moviestore_development_shard_two
    migration_paths: db/migrate_shards
  shard_three:
    <<: <%= ENV['DB_MODE'] ? "*#{ENV['DB_MODE']}" : "*mysql" %>
    database: moviestore_development_shard_three
    migration_paths: db/migrate_shards
  cache:
    <<: <%= ENV['DB_MODE'] ? "*#{ENV['DB_MODE']}" : "*mysql" %>
    database: moviestore_development_cache
    migration_paths: db/cache_migrate
  queue:
    <<: <%= ENV['DB_MODE'] ? "*#{ENV['DB_MODE']}" : "*mysql" %>
    database: moviestore_development_queue
    migration_paths: db/queue_migrate

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: <%= ENV['DB_MODE'] ? "*#{ENV['DB_MODE']}" : "*mysql" %>
  database: moviestore_test

production:
  <<: <%= ENV['DB_MODE'] ? "*#{ENV['DB_MODE']}" : "*mysql" %>
  database: moviestore_production
